version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: eventscheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/eventscheduler
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db

volumes:
  postgres_data: